"
I store metadata for the OpenPonk-OntoUML-ModelQuery package. This package provides a query API and utilities designed to extract, filter, and traverse structural and stereotypic data within OntoUML models.
"
Class {
	#name : 'ManifestOpenPonkOntoUMLModelQuery',
	#superclass : 'PackageManifest',
	#category : 'OpenPonk-OntoUML-ModelQuery-Manifest',
	#package : 'OpenPonk-OntoUML-ModelQuery',
	#tag : 'Manifest'
}
